name: CMake build matrix

on:
  push:
    branches:
      - master
  pull_request: {}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Cmake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make
